package sx.cfdi.providers.edicom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-16T23:05:31.970-06:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://cfdi.service.ediwinws.edicom.com", name = "CFDi")
@XmlSeeAlso({ObjectFactory.class})
public interface CFDi {

    @WebMethod
    @RequestWrapper(localName = "cancelaCFDiSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiSigned")
    @ResponseWrapper(localName = "cancelaCFDiSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiSignedResponse")
    @WebResult(name = "cancelaCFDiSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public sx.cfdi.providers.edicom.CancelaResponse cancelaCFDiSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdiAck", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiAck")
    @ResponseWrapper(localName = "getCfdiAckResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiAckResponse")
    @WebResult(name = "getCfdiAckReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdiAck(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTimbreCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiTest")
    @ResponseWrapper(localName = "getTimbreCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiTestResponse")
    @WebResult(name = "getTimbreCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getTimbreCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTimbreCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiRetenciones")
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiRetencionesResponse")
    @WebResult(name = "getTimbreCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getTimbreCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelaCFDi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDi")
    @ResponseWrapper(localName = "cancelaCFDiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiResponse")
    @WebResult(name = "cancelaCFDiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public sx.cfdi.providers.edicom.CancelaResponse cancelaCFDi(

        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,

        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,

        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,

        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String[] uuid,
        // java.util.List<java.lang.String> uuid,

        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,

        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String pfxPassword

    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetUUID")
    @ResponseWrapper(localName = "getUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetUUIDResponse")
    @WebResult(name = "getUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public java.lang.String getUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelaCFDiRetencionesSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiRetencionesSigned")
    @ResponseWrapper(localName = "cancelaCFDiRetencionesSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiRetencionesSignedResponse")
    @WebResult(name = "cancelaCFDiRetencionesSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public sx.cfdi.providers.edicom.CancelaResponse cancelaCFDiRetencionesSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiRetencionesTest")
    @ResponseWrapper(localName = "getCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiRetencionesTestResponse")
    @WebResult(name = "getCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdiFromUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiFromUUID")
    @ResponseWrapper(localName = "getCfdiFromUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiFromUUIDResponse")
    @WebResult(name = "getCfdiFromUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdiFromUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelaCFDiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiRetenciones")
    @ResponseWrapper(localName = "cancelaCFDiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.CancelaCFDiRetencionesResponse")
    @WebResult(name = "cancelaCFDiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public sx.cfdi.providers.edicom.CancelaResponse cancelaCFDiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String pfxPassword
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUUIDTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetUUIDTest")
    @ResponseWrapper(localName = "getUUIDTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetUUIDTestResponse")
    @WebResult(name = "getUUIDTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public java.lang.String getUUIDTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiTest")
    @ResponseWrapper(localName = "getCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiTestResponse")
    @WebResult(name = "getCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.ChangePasswordResponse")
    @WebResult(name = "changePasswordReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public boolean changePassword(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "newPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String newPassword
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTimbreCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdi")
    @ResponseWrapper(localName = "getTimbreCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiResponse")
    @WebResult(name = "getTimbreCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getTimbreCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "exportCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.ExportCfdi")
    @ResponseWrapper(localName = "exportCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.ExportCfdiResponse")
    @WebResult(name = "exportCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] exportCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "iniDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        javax.xml.datatype.XMLGregorianCalendar iniDate,
        @WebParam(name = "endDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTimbreCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiRetencionesTest")
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetTimbreCfdiRetencionesTestResponse")
    @WebResult(name = "getTimbreCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getTimbreCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiRetenciones")
    @ResponseWrapper(localName = "getCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiRetencionesResponse")
    @WebResult(name = "getCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdi")
    @ResponseWrapper(localName = "getCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "sx.cfdi.providers.edicom.GetCfdiResponse")
    @WebResult(name = "getCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    public byte[] getCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;
}
